Zephyr Scientific Library (zscilib): Operands
Operands
Matrices
Unary and binary operands that can be performed on matrix coefficients.
Functions
int zsl_mtx_unary_op (struct zsl_mtx *m, zsl_mtx_unary_op_t op)
Applies a unary operand on every coefficient in matrix 'm'.
int zsl_mtx_unary_func (struct zsl_mtx *m, zsl_mtx_unary_fn_t fn)
Applies a unary function on every coefficient in matrix 'm', using the specified 'zsl_mtx_apply_unary_fn_t' instance.
int zsl_mtx_binary_op (struct zsl_mtx *ma, struct zsl_mtx *mb, struct zsl_mtx *mc, zsl_mtx_binary_op_t op)
Applies a component-wise binary operation on every coefficient in symmetrical matrices 'ma' and 'mb', with the results being stored in the identically shaped mc matrix.
int zsl_mtx_binary_func (struct zsl_mtx *ma, struct zsl_mtx *mb, struct zsl_mtx *mc, zsl_mtx_binary_fn_t fn)
Applies a component-wise binary operztion on every coefficient in symmetrical matrices 'ma' and 'mb', with the results being stored in the identically shaped 'mc' matrix. The actual binary operation is executed using the specified 'zsl_mtx_binary_fn_t' callback.
Detailed Description
Unary and binary operands that can be performed on matrix coefficients.
Function Documentation
zsl_mtx_binary_func()
int zsl_mtx_binary_func (struct zsl_mtx * ma, struct zsl_mtx * mb, struct zsl_mtx * mc, zsl_mtx_binary_fn_t fn)
Applies a component-wise binary operztion on every coefficient in symmetrical matrices 'ma' and 'mb', with the results being stored in the identically shaped 'mc' matrix. The actual binary operation is executed using the specified 'zsl_mtx_binary_fn_t' callback.
Parameters
ma Pointer to first zsl_mtx to use in the binary operation.
mb Pointer to second zsl_mtx to use in the binary operation.
mc Pointer to output zsl_mtx used to store results.
fn The zsl_mtx_binary_fn_t instance to call.
Returns
0 on success, and non-zero error code on failure
Definition at line 350 of file matrices.c.
zsl_mtx_binary_op()
int zsl_mtx_binary_op (struct zsl_mtx * ma, struct zsl_mtx * mb, struct zsl_mtx * mc, zsl_mtx_binary_op_t op)
Applies a component-wise binary operation on every coefficient in symmetrical matrices 'ma' and 'mb', with the results being stored in the identically shaped mc matrix.
Parameters
ma Pointer to first zsl_mtx to use in the binary operation.
mb Pointer to second zsl_mtx to use in the binary operation.
mc Pointer to output zsl_mtx used to store results.
op The binary operation to apply to each coefficient.
Returns
0 on success, and non-zero error code on failure
Definition at line 289 of file matrices.c.
Referenced by zsl_mtx_add(), zsl_mtx_add_d(), zsl_mtx_sub(), and zsl_mtx_sub_d().
zsl_mtx_unary_func()
int zsl_mtx_unary_func (struct zsl_mtx * m, zsl_mtx_unary_fn_t fn)
Applies a unary function on every coefficient in matrix 'm', using the specified 'zsl_mtx_apply_unary_fn_t' instance.
Parameters
m Pointer to the zsl_mtx to use.
fn The zsl_mtx_unary_fn_t instance to call.
Returns
0 on success, and non-zero error code on failure
Definition at line 269 of file matrices.c.
zsl_mtx_unary_op()
int zsl_mtx_unary_op (struct zsl_mtx * m, zsl_mtx_unary_op_t op)
Applies a unary operand on every coefficient in matrix 'm'.
Parameters
m Pointer to the zsl_mtx to use.
op The unary operation to apply to each coefficient.
Returns
0 on success, and non-zero error code on failure
Definition at line 191 of file matrices.c.