Zephyr Scientific Library (zscilib): Functions
Functions
Quaternions
Quaternion APIU functionsn.
Functions
zsl_real_t zsl_quat_magn (struct zsl_quat *q)
Calculates the magnitude (or length) of the quaternion, a scalar value equal to the square root of the sum of the squares of the four components.
int zsl_quat_to_unit (struct zsl_quat *q, struct zsl_quat *qn)
Normalises the input to be a "unit" or "rotation" quaternion, AKA a versor, such that the square root of the sum of the squares of the four componeents, sqrt(r^2+i^2+j^2+k^2), equals 1.0. This normalisation process is what allows a quaternion to represent an rotation.
int zsl_quat_to_unit_d (struct zsl_quat *q)
Normalises to unit quaternion (destructive).
bool zsl_quat_is_unit (struct zsl_quat *q)
Verifies that this is a "unit" quaternion, meaning that it has a magnitude of 1, where sqrt(r^2+i^2+j^2+k^2) = 1.0.
int zsl_quat_scale (struct zsl_quat *q, zsl_real_t s, struct zsl_quat *qs)
Multiples each element in the quaternion by a scalar value.
int zsl_quat_scale_d (struct zsl_quat *q, zsl_real_t s)
Multiples each element in the quaternion by a scalar value (destructive).
int zsl_quat_mult (struct zsl_quat *qa, struct zsl_quat *qb, struct zsl_quat *qm)
Multiples the two supplied unit quaternions (a * b) together, and stores the results in qm.
int zsl_quat_exp (struct zsl_quat *q, struct zsl_quat *qe)
Calculates the exponential of a unit quaternion.
int zsl_quat_log (struct zsl_quat *q, struct zsl_quat *ql)
Calculates the natural logarithm of a unit quaternion.
int zsl_quat_pow (struct zsl_quat *q, zsl_real_t pow, struct zsl_quat *qout)
Multiples the supplied unit quaternions to the specified exponent, and stores the results in qout (where qout = qa^pow).
int zsl_quat_conj (struct zsl_quat *q, struct zsl_quat *qc)
Calculates the complex conjugate of 'q'.
int zsl_quat_inv (struct zsl_quat *q, struct zsl_quat *qi)
Calculates the multiplicative inverse of unit quaternion 'q'.
int zsl_quat_inv_d (struct zsl_quat *q)
Inverts unit quaternion 'q' (destructive).
int zsl_quat_diff (struct zsl_quat *qa, struct zsl_quat *qb, struct zsl_quat *qd)
Calculates the rotation (qd) from qa to qb using the multiplicative inverse, such that qb = qa * qd.
int zsl_quat_slerp (struct zsl_quat *qa, struct zsl_quat *qb, zsl_real_t t, struct zsl_quat *qi)
Spherical linear interpolation.
Detailed Description
Quaternion APIU functionsn.
Function Documentation
zsl_quat_conj()
int zsl_quat_conj (struct zsl_quat * q, struct zsl_quat * qc)
Calculates the complex conjugate of 'q'.
Parameters
q The input quaternion.
qc The conjugate output;
Returns
0 if everything executed normally, or a negative error code.
Definition at line 218 of file quaternions.c.
zsl_quat_diff()
int zsl_quat_diff (struct zsl_quat * qa, struct zsl_quat * qb, struct zsl_quat * qd)
Calculates the rotation (qd) from qa to qb using the multiplicative inverse, such that qb = qa * qd.
Parameters
qa The initial unit quaternion value.
qb The final unit quaternion value.
qd The difference as a quaternion.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 256 of file quaternions.c.
zsl_quat_exp()
int zsl_quat_exp (struct zsl_quat * q, struct zsl_quat * qe)
Calculates the exponential of a unit quaternion.
Parameters
q The input unit quaternion.
qe The output unit quaternion.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 130 of file quaternions.c.
Referenced by zsl_quat_pow().
zsl_quat_inv()
int zsl_quat_inv (struct zsl_quat * q, struct zsl_quat * qi)
Calculates the multiplicative inverse of unit quaternion 'q'.
Parameters
q The input unit quaternion.
qi The inverted output;
Returns
0 if everything executed normally, or a negative error code.
Definition at line 231 of file quaternions.c.
Referenced by zsl_quat_diff(), and zsl_quat_inv_d().
zsl_quat_inv_d()
int zsl_quat_inv_d (struct zsl_quat * q)
Inverts unit quaternion 'q' (destructive).
Parameters
q The input unit quaternion.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 251 of file quaternions.c.
zsl_quat_is_unit()
bool zsl_quat_is_unit (struct zsl_quat * q)
Verifies that this is a "unit" quaternion, meaning that it has a magnitude of 1, where sqrt(r^2+i^2+j^2+k^2) = 1.0.
Parameters
q The quaternion to verify.
Returns
true If this is a unit quaternion.
false If this is not a unit quaternion.
Definition at line 86 of file quaternions.c.
zsl_quat_log()
int zsl_quat_log (struct zsl_quat * q, struct zsl_quat * ql)
Calculates the natural logarithm of a unit quaternion.
Parameters
q The input unit quaternion.
qe The output unit quaternion.
Returns
zsl_real_t The logarithm of q.
Definition at line 161 of file quaternions.c.
Referenced by zsl_quat_pow().
zsl_quat_magn()
zsl_real_t zsl_quat_magn (struct zsl_quat * q)
Calculates the magnitude (or length) of the quaternion, a scalar value equal to the square root of the sum of the squares of the four components.
Note
A quaternion with a magnitude of 1 is referred to as a unit quaternion, and represents a rotation in 3D space.
Parameters
q The source quaternion.
Returns
zsl_real_t The magnitude of q.
Definition at line 56 of file quaternions.c.
Referenced by zsl_quat_inv(), zsl_quat_log(), and zsl_quat_to_unit().
zsl_quat_mult()
int zsl_quat_mult (struct zsl_quat * qa, struct zsl_quat * qb, struct zsl_quat * qm)
Multiples the two supplied unit quaternions (a * b) together, and stores the results in qm.
Note
Quaternion multiplication is not commutative, meaning that A*B != B*A. The order in which the quaternions appear when multiplying is important. To apply rotation q1, then rotation q2, we need to execute q3 = q2 * q1, in that order.
Parameters
qa The first input unit quaternion.
qb The second input unit quaternion.
qm The output placeholder.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 117 of file quaternions.c.
Referenced by zsl_quat_diff().
zsl_quat_pow()
int zsl_quat_pow (struct zsl_quat * q, zsl_real_t pow, struct zsl_quat * qout)
Multiples the supplied unit quaternions to the specified exponent, and stores the results in qout (where qout = qa^pow).
Parameters
q The input unit quaternion.
exp The exponent to use, where qa^exp.
qout The output placeholder.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 190 of file quaternions.c.
zsl_quat_scale()
int zsl_quat_scale (struct zsl_quat * q, zsl_real_t s, struct zsl_quat * qs)
Multiples each element in the quaternion by a scalar value.
Parameters
q The quaternion to scale.
s The scalar value to use.
qs The scaled output quaternion.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 100 of file quaternions.c.
Referenced by zsl_quat_pow(), and zsl_quat_scale_d().
zsl_quat_scale_d()
int zsl_quat_scale_d (struct zsl_quat * q, zsl_real_t s)
Multiples each element in the quaternion by a scalar value (destructive).
Parameters
q The quaternion to scale.
s The scalar value to use.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 112 of file quaternions.c.
zsl_quat_slerp()
int zsl_quat_slerp (struct zsl_quat * qa, struct zsl_quat * qb, zsl_real_t t, struct zsl_quat * qi)
Spherical linear interpolation.
Calculates an intermediate rotation between qa and qb, based on the provided interpolation factor, t (0.0..1.0). Output assigned to qi.
Parameters
qa The starting unit quaternion value.
qb The target unit quaternion value.
t The interpolation factor (0.0..1.0)
qi The interpolated quaternion.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 274 of file quaternions.c.
zsl_quat_to_unit()
int zsl_quat_to_unit (struct zsl_quat * q, struct zsl_quat * qn)
Normalises the input to be a "unit" or "rotation" quaternion, AKA a versor, such that the square root of the sum of the squares of the four componeents, sqrt(r^2+i^2+j^2+k^2), equals 1.0. This normalisation process is what allows a quaternion to represent an rotation.
Quaternion normalisation is required to represent rotation of objects in 3D space, and for transforming orientation coordinates in said space. You must normalise before using a quaternion to generate a rotation or transformation matrix, or to rotate or transform a vector.
Normalisation is accomplished by dividing each of the components by the square root of the sum of the squares of the four quaternion components (AKA the Euclidean norm).
To check if a quaternion is a unit quaternion, see zsl_quat_is_unit.
Parameters
q The source quaternion.
qn The normalised output quaternion.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 61 of file quaternions.c.
Referenced by zsl_quat_to_unit_d().
zsl_quat_to_unit_d()
int zsl_quat_to_unit_d (struct zsl_quat * q)
Normalises to unit quaternion (destructive).
Parameters
q The quaternion to normalise.
Returns
0 if everything executed normally, or a negative error code.
Definition at line 81 of file quaternions.c.