Zephyr Scientific Library (zscilib): Basic Math
Basic Math
Matrices | Vectors
Basic mathematical operations for matrices (add, substract, etc.).
Functions
int zsl_mtx_add (struct zsl_mtx *ma, struct zsl_mtx *mb, struct zsl_mtx *mc)
Adds matrices 'ma' and 'mb', assigning the output to 'mc'. Matrices 'ma', 'mb' and 'mc' must all be identically shaped.
int zsl_mtx_add_d (struct zsl_mtx *ma, struct zsl_mtx *mb)
Adds matrices 'ma' and 'mb', assigning the output to 'ma'. Matrices 'ma', and 'mb' must be identically shaped.
int zsl_mtx_sum_rows_d (struct zsl_mtx *m, size_t i, size_t j)
Adds the values of row 'j' to row 'i' in matrix 'm'. This operation is destructive for row 'i'.
int zsl_mtx_sum_rows_scaled_d (struct zsl_mtx *m, size_t i, size_t j, zsl_real_t s)
This function takes the coefficients of row 'j' and multiplies them by scalar 's', then adds the resulting coefficient to the parallel element in row 'i'. Row 'i' will be modified in this operation.
int zsl_mtx_sub (struct zsl_mtx *ma, struct zsl_mtx *mb, struct zsl_mtx *mc)
Subtracts matrices 'mb' from 'ma', assigning the output to 'mc'. Matrices 'ma', 'mb' and 'mc' must all be identically shaped.
int zsl_mtx_sub_d (struct zsl_mtx *ma, struct zsl_mtx *mb)
Subtracts matrix 'mb' from 'ma', assigning the output to 'ma'. Matrices 'ma', and 'mb' must be identically shaped.
int zsl_mtx_mult (struct zsl_mtx *ma, struct zsl_mtx *mb, struct zsl_mtx *mc)
Multiplies matrix 'ma' by 'mb', assigning the output to 'mc'. Matrices 'ma' and 'mb' must be compatibly shaped, meaning that 'ma' must have the same numbers of columns as there are rows in 'mb'.
int zsl_mtx_scalar_mult_d (struct zsl_mtx *m, zsl_real_t s)
Multiplies all elements in matrix 'm' by scalar value 's'.
int zsl_mtx_scalar_mult_row_d (struct zsl_mtx *m, size_t i, zsl_real_t s)
Multiplies the elements of row 'i' in matrix 'm' by scalar 's'.
int zsl_vec_add (struct zsl_vec *v, struct zsl_vec *w, struct zsl_vec *x)
Adds corresponding vector elements in 'v' and 'w', saving to 'x'.
int zsl_vec_sub (struct zsl_vec *v, struct zsl_vec *w, struct zsl_vec *x)
Subtracts corresponding vector elements in 'v' and 'w', saving to 'x'.
int zsl_vec_neg (struct zsl_vec *v)
Negates the elements in vector 'v'.
int zsl_vec_sum (struct zsl_vec **v, size_t n, struct zsl_vec *w)
Component-wise sum of a set of equal-length vectors.
zsl_real_t zsl_vec_magn (struct zsl_vec *v)
Computes the magnitude of a vector.
int zsl_vec_scalar_add (struct zsl_vec *v, zsl_real_t s)
Adds a scalar to each element in a vector.
int zsl_vec_scalar_mult (struct zsl_vec *v, zsl_real_t s)
Multiply a vector by a scalar.
int zsl_vec_scalar_div (struct zsl_vec *v, zsl_real_t s)
Divide a vector by a scalar.
zsl_real_t zsl_vec_dist (struct zsl_vec *v, struct zsl_vec *w)
Calculates the distance between two vectors, which is equal to the magnitude of vector v - vector w.
int zsl_vec_dot (struct zsl_vec *v, struct zsl_vec *w, zsl_real_t *d)
Computes the dot (aka scalar) product of two equal-length vectors (the sum of their component-wise products).
zsl_real_t zsl_vec_norm (struct zsl_vec *v)
Calculates the norm or absolute value of vector 'v' (the square root of the vector's dot product).
int zsl_vec_to_unit (struct zsl_vec *v)
Converts vector 'v' to a unit vector (a vector of length 1). This is accomploished by dividing each element by the it's norm.
int zsl_vec_cross (struct zsl_vec *v, struct zsl_vec *w, struct zsl_vec *c)
Computes the cross (or vector) product of two 3-vectors.
zsl_real_t zsl_vec_sum_of_sqrs (struct zsl_vec *v)
Computes the vector's sum of squares.
int zsl_vec_mean (struct zsl_vec **v, size_t n, struct zsl_vec *m)
Computes the component-wise mean of a set of identically-sized vectors.
int zsl_vec_ar_mean (struct zsl_vec *v, zsl_real_t *m)
Computes the arithmetic mean of a vector.
int zsl_vec_rev (struct zsl_vec *v)
Reverses the order of the entries in vector 'v'.
Detailed Description
Basic mathematical operations for matrices (add, substract, etc.).
Basic mathematical operations (add, sum, magnitude, etc.).
Function Documentation
zsl_mtx_add()
int zsl_mtx_add (struct zsl_mtx * ma, struct zsl_mtx * mb, struct zsl_mtx * mc)
Adds matrices 'ma' and 'mb', assigning the output to 'mc'. Matrices 'ma', 'mb' and 'mc' must all be identically shaped.
Parameters
ma Pointer to the first input zsl_mtx.
mb Pointer to the second input zsl_mtx.
mc Pointer to the output zsl_mtx.
Returns
0 if everything executed correctly, or -EINVAL if the three matrices are not all identically shaped.
Definition at line 378 of file matrices.c.
zsl_mtx_add_d()
int zsl_mtx_add_d (struct zsl_mtx * ma, struct zsl_mtx * mb)
Adds matrices 'ma' and 'mb', assigning the output to 'ma'. Matrices 'ma', and 'mb' must be identically shaped.
Parameters
ma Pointer to the first input zsl_mtx. This matrix will be overwritten with the results of the addition operations!
mb Pointer to the second input zsl_mtx.
Warning
This function is destructive to 'ma'!
Returns
0 if everything executed correctly, or -EINVAL if the two input matrices are not identically shaped.
Definition at line 384 of file matrices.c.
zsl_mtx_mult()
int zsl_mtx_mult (struct zsl_mtx * ma, struct zsl_mtx * mb, struct zsl_mtx * mc)
Multiplies matrix 'ma' by 'mb', assigning the output to 'mc'. Matrices 'ma' and 'mb' must be compatibly shaped, meaning that 'ma' must have the same numbers of columns as there are rows in 'mb'.
Parameters
ma Pointer to the first input zsl_mtx.
mb Pointer to the second input zsl_mtx.
mc Pointer to the output zsl_mtx.
Returns
0 if everything executed correctly, or -EINVAL if the input matrices are not compatibly shaped.
Definition at line 437 of file matrices.c.
zsl_mtx_scalar_mult_d()
int zsl_mtx_scalar_mult_d (struct zsl_mtx * m, zsl_real_t s)
Multiplies all elements in matrix 'm' by scalar value 's'.
Parameters
m Pointer to the zsl_mtz to adjust.
s The scalar value to multiply elements in matrix 'm' with.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 466 of file matrices.c.
Referenced by zsl_mtx_inv_3x3().
zsl_mtx_scalar_mult_row_d()
int zsl_mtx_scalar_mult_row_d (struct zsl_mtx * m, size_t i, zsl_real_t s)
Multiplies the elements of row 'i' in matrix 'm' by scalar 's'.
Parameters
m Pointer to the zsl_mtx to use.
i The row number to multiply by scalar 's' (0-based).
s The scalar to use when multiplying elements of row 'i'.
Returns
0 if everything executed correctly, or -EINVAL on an out of bounds error.
Definition at line 476 of file matrices.c.
Referenced by zsl_mtx_norm_elem().
zsl_mtx_sub()
int zsl_mtx_sub (struct zsl_mtx * ma, struct zsl_mtx * mb, struct zsl_mtx * mc)
Subtracts matrices 'mb' from 'ma', assigning the output to 'mc'. Matrices 'ma', 'mb' and 'mc' must all be identically shaped.
Parameters
ma Pointer to the first input zsl_mtx.
mb Pointer to the second input zsl_mtx.
mc Pointer to the output zsl_mtx.
Returns
0 if everything executed correctly, or -EINVAL if the three matrices are not all identically shaped.
Definition at line 425 of file matrices.c.
zsl_mtx_sub_d()
int zsl_mtx_sub_d (struct zsl_mtx * ma, struct zsl_mtx * mb)
Subtracts matrix 'mb' from 'ma', assigning the output to 'ma'. Matrices 'ma', and 'mb' must be identically shaped.
Parameters
ma Pointer to the first input zsl_mtx. This matrix will be overwritten with the results of the subtraction operations!
mb Pointer to the second input zsl_mtx.
Warning
This function is destructive to 'ma'!
Returns
0 if everything executed correctly, or -EINVAL if the two input matrices are not identically shaped.
Definition at line 431 of file matrices.c.
zsl_mtx_sum_rows_d()
int zsl_mtx_sum_rows_d (struct zsl_mtx * m, size_t i, size_t j)
Adds the values of row 'j' to row 'i' in matrix 'm'. This operation is destructive for row 'i'.
Parameters
m Pointer to the zsl_mtx to use.
i The first row number to add (0-based).
j The second row number to add (0-based).
Returns
0 if everything executed correctly, or -EINVAL on an out of bounds error.
Definition at line 390 of file matrices.c.
Referenced by zsl_mtx_inv().
zsl_mtx_sum_rows_scaled_d()
int zsl_mtx_sum_rows_scaled_d (struct zsl_mtx * m, size_t i, size_t j, zsl_real_t s)
This function takes the coefficients of row 'j' and multiplies them by scalar 's', then adds the resulting coefficient to the parallel element in row 'i'. Row 'i' will be modified in this operation.
This function implements a key mechanism of Gauss–Jordan elimination, as can be seen in zsl_mtx_gauss_elim.
Parameters
m Pointer to the zsl_mtx to use.
i The row number to update (0-based).
j The row number to scale and then add to 'i' (0-based).
s The scalar value to apply to the values in row 'j'.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 406 of file matrices.c.
Referenced by zsl_mtx_gauss_elim().
zsl_vec_add()
int zsl_vec_add (struct zsl_vec * v, struct zsl_vec * w, struct zsl_vec * x)
Adds corresponding vector elements in 'v' and 'w', saving to 'x'.
Parameters
v The first vector.
w The second vector.
x The output vector.
Returns
0 on success, -EINVAL if v and w are not equal length.
Definition at line 57 of file vectors.c.
zsl_vec_ar_mean()
int zsl_vec_ar_mean (struct zsl_vec * v, zsl_real_t * m)
Computes the arithmetic mean of a vector.
Parameters
v The vector to use.
m The arithmetic mean of vector v.
Returns
0 on success, otherwise an appropriate error code.
Definition at line 289 of file vectors.c.
zsl_vec_cross()
int zsl_vec_cross (struct zsl_vec * v, struct zsl_vec * w, struct zsl_vec * c)
Computes the cross (or vector) product of two 3-vectors.
Parameters
v The first 3-vector.
w The second 3-vector.
c The cross product 3-vector output.
Returns
0 on success, or -EINVAL if a non 3-vector is provided.
Given two linearly independent 3-vectors (v and w), the cross product, (v X w), is a vector that is perpendicular to both v and w and thus 'normal' to the plane containing them.
If two vectors have the same direction (or have the exact opposite direction from one another, i.e. are not linearly independent) or if either one has zero length, then their cross product is zero.
The magnitude of the cross product equals the area of a parallelogram with vectors v and w for sides.
For a discusson of geometric and algebraic applications, see: https://en.wikipedia.org/wiki/Cross_product
Definition at line 231 of file vectors.c.
zsl_vec_dist()
zsl_real_t zsl_vec_dist (struct zsl_vec * v, struct zsl_vec * w)
Calculates the distance between two vectors, which is equal to the magnitude of vector v - vector w.
Parameters
v The first vector.
w The second vector.
Returns
The magnitude of vector v - vector w, or NAN is there was a size mismatch between vectors v and w.
Definition at line 159 of file vectors.c.
zsl_vec_dot()
int zsl_vec_dot (struct zsl_vec * v, struct zsl_vec * w, zsl_real_t * d)
Computes the dot (aka scalar) product of two equal-length vectors (the sum of their component-wise products).
Parameters
v The first vector.
w The second vector.
d The dot product.
Returns
0 on success, or -EINVAL if vectors v and w aren't equal-length.
Definition at line 176 of file vectors.c.
Referenced by zsl_vec_sum_of_sqrs().
zsl_vec_magn()
zsl_real_t zsl_vec_magn (struct zsl_vec * v)
Computes the magnitude of a vector.
Parameters
v The vector to use.
Returns
The magnitude of vector 'v'.
Definition at line 124 of file vectors.c.
Referenced by zsl_vec_dist().
zsl_vec_mean()
int zsl_vec_mean (struct zsl_vec ** v, size_t n, struct zsl_vec * m)
Computes the component-wise mean of a set of identically-sized vectors.
Parameters
v Pointer to the array of vectors.
n The number of vectors in 'v'.
m Pointer to the output vector whose i'th element is the mean of the i'th elements of the input vectors.
Returns
0 on success, and -EINVAL if all vectors aren't identically sized.
Definition at line 268 of file vectors.c.
zsl_vec_neg()
int zsl_vec_neg (struct zsl_vec * v)
Negates the elements in vector 'v'.
Parameters
v The vector to negate.
Returns
0 on success, and non-zero error code on failure
Definition at line 87 of file vectors.c.
zsl_vec_norm()
zsl_real_t zsl_vec_norm (struct zsl_vec * v)
Calculates the norm or absolute value of vector 'v' (the square root of the vector's dot product).
Parameters
v The vector to calculate the norm of.
Returns
The norm of vector 'v'.
Definition at line 195 of file vectors.c.
Referenced by zsl_vec_to_unit().
zsl_vec_rev()
int zsl_vec_rev (struct zsl_vec * v)
Reverses the order of the entries in vector 'v'.
Parameters
v The vector to use.
Returns
0 on success, otherwise an appropriate error code.
Definition at line 305 of file vectors.c.
zsl_vec_scalar_add()
int zsl_vec_scalar_add (struct zsl_vec * v, zsl_real_t s)
Adds a scalar to each element in a vector.
Parameters
v The vector to scale.
s The scalar to add to each element.
Returns
0 on success, and non-zero error code on failure
Definition at line 128 of file vectors.c.
zsl_vec_scalar_div()
int zsl_vec_scalar_div (struct zsl_vec * v, zsl_real_t s)
Divide a vector by a scalar.
Parameters
v The vector to scale.
s The scalar to divide all elements by.
Returns
0 on success, and non-zero error code on failure
Definition at line 146 of file vectors.c.
zsl_vec_scalar_mult()
int zsl_vec_scalar_mult (struct zsl_vec * v, zsl_real_t s)
Multiply a vector by a scalar.
Parameters
v The vector to scale.
s The scalar to multiply by.
Returns
0 on success, and non-zero error code on failure
Definition at line 137 of file vectors.c.
Referenced by zsl_vec_mean(), and zsl_vec_to_unit().
zsl_vec_sub()
int zsl_vec_sub (struct zsl_vec * v, struct zsl_vec * w, struct zsl_vec * x)
Subtracts corresponding vector elements in 'v' and 'w', saving to 'x'.
Parameters
v The first vector.
w The second vector.
x The output vector.
Returns
0 on success, -EINVAL if v and w are not equal length.
Definition at line 72 of file vectors.c.
Referenced by zsl_vec_dist().
zsl_vec_sum()
int zsl_vec_sum (struct zsl_vec ** v, size_t n, struct zsl_vec * w)
Component-wise sum of a set of equal-length vectors.
Parameters
v Pointer to the array of vectors.
n The number of vectors in 'v'.
w Pointer to the output vector containing the component-wise sum.
Returns
0 on success, -EINVAL if vectors in 'v' are no equal length, or -EINVAL if 'n' = 0.
Definition at line 95 of file vectors.c.
Referenced by zsl_vec_mean().
zsl_vec_sum_of_sqrs()
zsl_real_t zsl_vec_sum_of_sqrs (struct zsl_vec * v)
Computes the vector's sum of squares.
Parameters
v The vector to use.
Returns
The sum of the squares of vector 'v'.
Definition at line 260 of file vectors.c.
Referenced by zsl_vec_magn().
zsl_vec_to_unit()
int zsl_vec_to_unit (struct zsl_vec * v)
Converts vector 'v' to a unit vector (a vector of length 1). This is accomploished by dividing each element by the it's norm.
Parameters
v The vector to convert to a unit vector.
Returns
0 on success, and non-zero error code on failure
Definition at line 209 of file vectors.c.