Zephyr Scientific Library (zscilib): Transformation
Transformation
Matrices
Transformation functions for matrices (transpose, inverse, guassian elimination, etc.).
Functions
int zsl_mtx_trans (struct zsl_mtx *ma, struct zsl_mtx *mb)
Transposes the matrix 'ma' into matrix 'mb'. Note that output matrix 'mb' must have 'ma->sz_rows' columns, and 'ma->sz_cols' rows.
int zsl_mtx_adjoint_3x3 (struct zsl_mtx *m, struct zsl_mtx *ma)
Calculates the ajoint matrix, based on the input 3x3 matrix 'm'.
int zsl_mtx_adjoint (struct zsl_mtx *m, struct zsl_mtx *ma)
Calculates the ajoint matrix, based on the input square matrix 'm'.
int zsl_mtx_vec_wedge (struct zsl_mtx *m, struct zsl_vec *v)
Calculates the wedge product of n-1 vectors of size n, which are the rows of the matrix 'm'. This n-1 vectors must be linearly independent.
int zsl_mtx_reduce (struct zsl_mtx *m, struct zsl_mtx *mr, size_t i, size_t j)
Removes row 'i' and column 'j' from square matrix 'm', assigning the remaining elements in the matrix to 'mr'.
int zsl_mtx_reduce_iter (struct zsl_mtx *m, struct zsl_mtx *mred)
Reduces the number of rows/columns in the input square matrix 'm' to match the shape of 'mred', where mred < m. Rows/cols will be removed starting on the left and upper vectors.
int zsl_mtx_augm_diag (struct zsl_mtx *m, struct zsl_mtx *maug)
Augments the input square matrix with additional rows and columns, based on the size 'diff' between m and maug (where maug > m). New rows and columns are assigned values based on an identity matrix, meaning 1.0 on the new diagonal values and 0.0 above and below the diagonal.
int zsl_mtx_deter_3x3 (struct zsl_mtx *m, zsl_real_t *d)
Calculates the determinant of the input 3x3 matrix 'm'.
int zsl_mtx_deter (struct zsl_mtx *m, zsl_real_t *d)
Calculates the determinant of the input square matrix 'm'.
int zsl_mtx_gauss_elim (struct zsl_mtx *m, struct zsl_mtx *mg, struct zsl_mtx *mi, size_t i, size_t j)
Given the element (i,j) in matrix 'm', this function performs gaussian elimination by adding row 'i' to the other rows until all of the elements in column 'j' are equal to 0.0, aside from the element at position (i, j). The result of this process will be assigned to matrix 'mg'.
int zsl_mtx_gauss_elim_d (struct zsl_mtx *m, struct zsl_mtx *mi, size_t i, size_t j)
Given the element (i,j) in matrix 'm', this function performs gaussian elimination by adding row 'i' to the other rows until all of the elements in column 'j' are equal to 0.0, aside from the element at position (i, j). This function is destructive and will modify the contents of m.
int zsl_mtx_gauss_reduc (struct zsl_mtx *m, struct zsl_mtx *mi, struct zsl_mtx *mg)
Given matrix 'm', puts the matrix into echelon form using Gauss-Jordan reduction.
int zsl_mtx_cols_norm (struct zsl_mtx *m, struct zsl_mtx *mnorm)
Updates the values of every column vector in input matrix 'm' to have unitary values.
int zsl_mtx_gram_schmidt (struct zsl_mtx *m, struct zsl_mtx *mort)
Performs the Gram-Schmidt algorithm on the set of column vectors in matrix 'm'. This algorithm calculates a set of orthogonal vectors in the same vectorial space as the original vectors.
int zsl_mtx_norm_elem (struct zsl_mtx *m, struct zsl_mtx *mn, struct zsl_mtx *mi, size_t i, size_t j)
Normalises elements in matrix m such that the element at position (i, j) is equal to 1.0.
int zsl_mtx_norm_elem_d (struct zsl_mtx *m, struct zsl_mtx *mi, size_t i, size_t j)
Normalises elements in matrix m such that the element at position (i, j) is equal to 1.0. This function is destructive and will modify the contents of m.
int zsl_mtx_inv_3x3 (struct zsl_mtx *m, struct zsl_mtx *mi)
Calculates the inverse of 3x3 matrix 'm'. If the determinant of 'm' is zero, an identity matrix will be returned via 'mi'.
int zsl_mtx_inv (struct zsl_mtx *m, struct zsl_mtx *mi)
Calculates the inverse of square matrix 'm'.
int zsl_mtx_cholesky (struct zsl_mtx *m, struct zsl_mtx *l)
Calculates the Cholesky decomposition of a symmetric square matrix using the Cholesky–Crout algorithm.
int zsl_mtx_balance (struct zsl_mtx *m, struct zsl_mtx *mout)
Balances the square matrix 'm', a process in which the eigenvalues of the output matrix are the same as the eigenvalues of the input matrix.
int zsl_mtx_householder (struct zsl_mtx *m, struct zsl_mtx *h, bool hessenberg)
Calculates the householder reflection of 'm'. Used as part of QR decomposition. When 'hessenberg' is active, it calculates the householder reflection but without using the first line of 'm'.
int zsl_mtx_qrd (struct zsl_mtx *m, struct zsl_mtx *q, struct zsl_mtx *r, bool hessenberg)
If 'hessenberg' is set to false, this function performs the QR decomposition, which is a factorisation of matrix 'm' into an orthogonal matrix (q) and an upper triangular matrix (r). If 'hessenberg' is set to true, this function puts the matrix 'm' into hessenberg form. This function uses the householder reflections.
int zsl_mtx_qrd_iter (struct zsl_mtx *m, struct zsl_mtx *mout, size_t iter)
Computes recursively the QR decompisition method to put the input square matrix into upper triangular form.
int zsl_mtx_eigenvalues (struct zsl_mtx *m, struct zsl_vec *v, size_t iter)
Calculates the eigenvalues for input matrix 'm' using QR decomposition recursively. The output vector will only contain real eigenvalues, even if the input matrix has complex eigenvalues.
int zsl_mtx_eigenvectors (struct zsl_mtx *m, struct zsl_mtx *mev, size_t iter, bool orthonormal)
Calcualtes the set of eigenvectors for input matrix 'm', using the specified number of iterations to find a balance between precision and processing effort. Optionally, the output eigenvectors can be orthonormalised.
int zsl_mtx_svd (struct zsl_mtx *m, struct zsl_mtx *u, struct zsl_mtx *e, struct zsl_mtx *v, size_t iter)
Performs singular value decomposition, converting input matrix 'm' into matrices 'u', 'e', and 'v'.
int zsl_mtx_pinv (struct zsl_mtx *m, struct zsl_mtx *pinv, size_t iter)
Performs the pseudo-inverse (aka pinv or Moore-Penrose inverse) on input matrix 'm'.
Detailed Description
Transformation functions for matrices (transpose, inverse, guassian elimination, etc.).
Function Documentation
zsl_mtx_adjoint()
int zsl_mtx_adjoint (struct zsl_mtx * m, struct zsl_mtx * ma)
Calculates the ajoint matrix, based on the input square matrix 'm'.
Parameters
m The input square matrix to use.
ma The output square matrix the adjoint values will be assigned to.
Returns
0 if everything executed correctly, or -EINVAL if this isn't a square matrix.
Definition at line 572 of file matrices.c.
zsl_mtx_adjoint_3x3()
int zsl_mtx_adjoint_3x3 (struct zsl_mtx * m, struct zsl_mtx * ma)
Calculates the ajoint matrix, based on the input 3x3 matrix 'm'.
Parameters
m The input 3x3 square matrix to use.
ma The output 3x3 square matrix the adjoint values will be assigned to.
Returns
0 if everything executed correctly, or -EINVAL if this isn't a 3x3 square matrix.
Definition at line 534 of file matrices.c.
Referenced by zsl_mtx_adjoint(), and zsl_mtx_inv_3x3().
zsl_mtx_augm_diag()
int zsl_mtx_augm_diag (struct zsl_mtx * m, struct zsl_mtx * maug)
Augments the input square matrix with additional rows and columns, based on the size 'diff' between m and maug (where maug > m). New rows and columns are assigned values based on an identity matrix, meaning 1.0 on the new diagonal values and 0.0 above and below the diagonal.
Parameters
m Pointer to the input square matrix.
maug Pointer the the augmented output square matrix.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 696 of file matrices.c.
Referenced by zsl_mtx_householder(), and zsl_mtx_qrd().
zsl_mtx_balance()
int zsl_mtx_balance (struct zsl_mtx * m, struct zsl_mtx * mout)
Balances the square matrix 'm', a process in which the eigenvalues of the output matrix are the same as the eigenvalues of the input matrix.
Parameters
m The input square matrix to use.
mout The output balanced matrix.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 1173 of file matrices.c.
Referenced by zsl_mtx_eigenvalues().
zsl_mtx_cholesky()
int zsl_mtx_cholesky (struct zsl_mtx * m, struct zsl_mtx * l)
Calculates the Cholesky decomposition of a symmetric square matrix using the Cholesky–Crout algorithm.
Computing the Cholesky decomposition of a symmetric square matrix M consists in finding a matrix L such that M = L * Lt (L multiplied by its transpose).
Parameters
m The input symmetric square matrix to use.
l The output lower triangular matrix.
Returns
0 if everything executed correctly, or -EINVAL if 'm' isn't a symmetric square matrix.
Definition at line 1116 of file matrices.c.
zsl_mtx_cols_norm()
int zsl_mtx_cols_norm (struct zsl_mtx * m, struct zsl_mtx * mnorm)
Updates the values of every column vector in input matrix 'm' to have unitary values.
Parameters
m Pointer to the input matrix.
mnorm Pointer to the output matrix where the columns are unitary vectors.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 951 of file matrices.c.
Referenced by zsl_mtx_eigenvectors().
zsl_mtx_deter()
int zsl_mtx_deter (struct zsl_mtx * m, zsl_real_t * d)
Calculates the determinant of the input square matrix 'm'.
Parameters
m The input square matrix to use.
d The determinant of square matrix m.
Returns
0 if everything executed correctly, or -EINVAL if this isn't a square matrix.
Definition at line 744 of file matrices.c.
Referenced by zsl_mtx_adjoint(), zsl_mtx_inv(), zsl_mtx_vec_wedge(), zsl_sta_mult_linear_reg(), and zsl_sta_weighted_mult_linear_reg().
zsl_mtx_deter_3x3()
int zsl_mtx_deter_3x3 (struct zsl_mtx * m, zsl_real_t * d)
Calculates the determinant of the input 3x3 matrix 'm'.
Parameters
m The input 3x3 square matrix to use.
d The determinant of 3x3 square matrix m.
Returns
0 on success, or -EINVAL if this isn't a 3x3 square matrix.
Definition at line 714 of file matrices.c.
Referenced by zsl_mtx_deter(), and zsl_mtx_inv_3x3().
zsl_mtx_eigenvalues()
int zsl_mtx_eigenvalues (struct zsl_mtx * m, struct zsl_vec * v, size_t iter)
Calculates the eigenvalues for input matrix 'm' using QR decomposition recursively. The output vector will only contain real eigenvalues, even if the input matrix has complex eigenvalues.
Parameters
m The input square matrix to use.
v The placeholder for the output vector where the real eigenvalues should be stored.
iter The number of times that 'zsl_mtx_qrd' should be called during the QR decomposition phase.
NOTE: Large values required more iterations to get precise results, and some trial and error may be required to find the right balance of iterations versus processing time.
Returns
0 if everything executed correctly, otherwise an appropriate error code. If -ECOMPLEXVAL is returned, it means that complex numbers were detected in the output eigenvalues.
Definition at line 1398 of file matrices.c.
Referenced by zsl_mtx_eigenvectors(), and zsl_mtx_svd().
zsl_mtx_eigenvectors()
int zsl_mtx_eigenvectors (struct zsl_mtx * m, struct zsl_mtx * mev, size_t iter, bool orthonormal)
Calcualtes the set of eigenvectors for input matrix 'm', using the specified number of iterations to find a balance between precision and processing effort. Optionally, the output eigenvectors can be orthonormalised.
Parameters
m The input square matrix to use.
mev The placeholder for the output square matrix where the eigenvectors should be stored as column vectors.
iter The number of times that 'zsl_mtx_qrd' should be called. during the QR decomposition phase.
orthonormal If set to true, the output matrix 'mev' will be orthonormalised.
NOTE: Large values required more iterations to get precise results, and some trial and error may be required to find the right balance of iterations versus processing time.
Returns
0 if everything executed correctly, otherwise an appropriate error code. If the number of calcualted eigenvectors is less than the columns in 'm', EEIGENSIZE will be returned.
Definition at line 1504 of file matrices.c.
Referenced by zsl_mtx_svd().
zsl_mtx_gauss_elim()
int zsl_mtx_gauss_elim (struct zsl_mtx * m, struct zsl_mtx * mg, struct zsl_mtx * mi, size_t i, size_t j)
Given the element (i,j) in matrix 'm', this function performs gaussian elimination by adding row 'i' to the other rows until all of the elements in column 'j' are equal to 0.0, aside from the element at position (i, j). The result of this process will be assigned to matrix 'mg'.
Parameters
m Pointer to input zsl_mtx to use.
mg Pointer to gaussian form output matrix.
mi Pointer to the identity output matrix.
i The row number of the element to use (0-based).
j The column number of the element to use (0-based).
Returns
0 on success, and non-zero error code on failure
Definition at line 809 of file matrices.c.
Referenced by zsl_mtx_gauss_elim_d().
zsl_mtx_gauss_elim_d()
int zsl_mtx_gauss_elim_d (struct zsl_mtx * m, struct zsl_mtx * mi, size_t i, size_t j)
Given the element (i,j) in matrix 'm', this function performs gaussian elimination by adding row 'i' to the other rows until all of the elements in column 'j' are equal to 0.0, aside from the element at position (i, j). This function is destructive and will modify the contents of m.
Parameters
m Pointer to zsl_mtx to use.
mi Pointer to the identity output matrix.
i The row number of the element to use (0-based).
j The column number of the element to use (0-based).
Returns
0 on success, and non-zero error code on failure
Definition at line 861 of file matrices.c.
Referenced by zsl_mtx_gauss_reduc().
zsl_mtx_gauss_reduc()
int zsl_mtx_gauss_reduc (struct zsl_mtx * m, struct zsl_mtx * mi, struct zsl_mtx * mg)
Given matrix 'm', puts the matrix into echelon form using Gauss-Jordan reduction.
Parameters
m Pointer to the input square matrix to use.
mi Pointer to the identity output matrix.
mg Pointer to the output square matrix in echelon form.
Returns
0 on success, and non-zero error code on failure
Definition at line 867 of file matrices.c.
Referenced by zsl_mtx_eigenvectors(), and zsl_mtx_inv().
zsl_mtx_gram_schmidt()
int zsl_mtx_gram_schmidt (struct zsl_mtx * m, struct zsl_mtx * mort)
Performs the Gram-Schmidt algorithm on the set of column vectors in matrix 'm'. This algorithm calculates a set of orthogonal vectors in the same vectorial space as the original vectors.
Parameters
m Pointer to the input matrix containing the vector data.
mort Pointer to the output matrix containing the orthogonal vector data.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 922 of file matrices.c.
Referenced by zsl_mtx_eigenvectors().
zsl_mtx_householder()
int zsl_mtx_householder (struct zsl_mtx * m, struct zsl_mtx * h, bool hessenberg)
Calculates the householder reflection of 'm'. Used as part of QR decomposition. When 'hessenberg' is active, it calculates the householder reflection but without using the first line of 'm'.
Parameters
m Pointer to the input matrix to use.
hessenberg If set to true, the first line in 'm' is ignored.
h Pointer to the output square matrix where the values of the householder reflection should be assigned.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 1254 of file matrices.c.
Referenced by zsl_mtx_qrd().
zsl_mtx_inv()
int zsl_mtx_inv (struct zsl_mtx * m, struct zsl_mtx * mi)
Calculates the inverse of square matrix 'm'.
Parameters
m The input square matrix to use.
mi The output inverse square matrix.
Returns
0 if everything executed correctly, or -EINVAL if this isn't a square matrix.
Definition at line 1064 of file matrices.c.
Referenced by zsl_mtx_vec_wedge(), zsl_sta_mult_linear_reg(), zsl_sta_quad_fit(), and zsl_sta_weighted_mult_linear_reg().
zsl_mtx_inv_3x3()
int zsl_mtx_inv_3x3 (struct zsl_mtx * m, struct zsl_mtx * mi)
Calculates the inverse of 3x3 matrix 'm'. If the determinant of 'm' is zero, an identity matrix will be returned via 'mi'.
Parameters
m The input 3x3 matrix to use.
mi The output inverse 3x3 matrix.
Returns
0 if everything executed correctly, or -EINVAL if this isn't a 3x3 matrix.
Definition at line 1009 of file matrices.c.
Referenced by zsl_mtx_inv().
zsl_mtx_norm_elem()
int zsl_mtx_norm_elem (struct zsl_mtx * m, struct zsl_mtx * mn, struct zsl_mtx * mi, size_t i, size_t j)
Normalises elements in matrix m such that the element at position (i, j) is equal to 1.0.
Parameters
m Pointer to input zsl_mtx to use.
mn Pointer to normalised output zsl_mtx.
mi Pointer to the output identity zsl_mtx.
i The row number of the element to use (0-based).
j The column number of the element to use (0-based).
Returns
0 on success, and non-zero error code on failure
Definition at line 965 of file matrices.c.
Referenced by zsl_mtx_norm_elem_d().
zsl_mtx_norm_elem_d()
int zsl_mtx_norm_elem_d (struct zsl_mtx * m, struct zsl_mtx * mi, size_t i, size_t j)
Normalises elements in matrix m such that the element at position (i, j) is equal to 1.0. This function is destructive and will modify the contents of m.
Parameters
m Pointer to zsl_mtx to use.
mi Pointer to the output identity zsl_mtx.
i The row number of the element to use (0-based).
j The column number of the element to use (0-based).
Returns
0 on success, and non-zero error code on failure
Definition at line 1003 of file matrices.c.
Referenced by zsl_mtx_gauss_reduc().
zsl_mtx_pinv()
int zsl_mtx_pinv (struct zsl_mtx * m, struct zsl_mtx * pinv, size_t iter)
Performs the pseudo-inverse (aka pinv or Moore-Penrose inverse) on input matrix 'm'.
Parameters
m The input mxn matrix to use.
pinv The placeholder for the output pseudo inverse nxm matrix.
iter The number of times that 'zsl_mtx_qrd' should be called. during the QR decomposition phase.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 1734 of file matrices.c.
zsl_mtx_qrd()
int zsl_mtx_qrd (struct zsl_mtx * m, struct zsl_mtx * q, struct zsl_mtx * r, bool hessenberg)
If 'hessenberg' is set to false, this function performs the QR decomposition, which is a factorisation of matrix 'm' into an orthogonal matrix (q) and an upper triangular matrix (r). If 'hessenberg' is set to true, this function puts the matrix 'm' into hessenberg form. This function uses the householder reflections.
One of the uses of this function is to make use of the householder method to perform the QR decomposition, which introduces the zeros below the diagonal of matrix 'r'. Other algorithms exist, such as the Gram-Schmidt process, but they tend to be less stable than the householder method for a similar computational cost.
Parameters
m Pointer to the input square matrix.
q Pointer to the output orthoogonal square matrix.
r Pointer to the output upper triangular square matrix or hessenberg matrix if set to true.
hessenberg Sets the matrix to hessenberg format if 'true'.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 1318 of file matrices.c.
Referenced by zsl_mtx_eigenvalues(), and zsl_mtx_qrd_iter().
zsl_mtx_qrd_iter()
int zsl_mtx_qrd_iter (struct zsl_mtx * m, struct zsl_mtx * mout, size_t iter)
Computes recursively the QR decompisition method to put the input square matrix into upper triangular form.
Parameters
m The input square matrix to use when performing the QR decomposition.
mout The output upper triangular square matrix where the results should be stored.
iter The number of times that 'zsl_mtx_qrd' should be called.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 1369 of file matrices.c.
Referenced by zsl_mtx_eigenvalues().
zsl_mtx_reduce()
int zsl_mtx_reduce (struct zsl_mtx * m, struct zsl_mtx * mr, size_t i, size_t j)
Removes row 'i' and column 'j' from square matrix 'm', assigning the remaining elements in the matrix to 'mr'.
Parameters
m The input nxn square matrix to use.
mr The output (n-1)x(n-1) square matrix.
i The row number to remove (0-based).
j The column number to remove (0-based).
Returns
0 if everything executed correctly, or -EINVAL if this isn't a square matrix.
Definition at line 645 of file matrices.c.
Referenced by zsl_mtx_adjoint(), zsl_mtx_deter(), and zsl_mtx_reduce_iter().
zsl_mtx_reduce_iter()
int zsl_mtx_reduce_iter (struct zsl_mtx * m, struct zsl_mtx * mred)
Reduces the number of rows/columns in the input square matrix 'm' to match the shape of 'mred', where mred < m. Rows/cols will be removed starting on the left and upper vectors.
Parameters
m Pointer to the input square matrix.
mred Pointer the the reduced output square matrix.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 680 of file matrices.c.
Referenced by zsl_mtx_qrd().
zsl_mtx_svd()
int zsl_mtx_svd (struct zsl_mtx * m, struct zsl_mtx * u, struct zsl_mtx * e, struct zsl_mtx * v, size_t iter)
Performs singular value decomposition, converting input matrix 'm' into matrices 'u', 'e', and 'v'.
Parameters
m The input mxn matrix to use.
u The placeholder for the output mxm matrix u.
e The placeholder for the output mxn matrix sigma.
v The placeholder for the output nxn matrix v.
iter The number of times that 'zsl_mtx_qrd' should be called. during the QR decomposition phase.
Returns
0 if everything executed correctly, otherwise an appropriate error code.
Definition at line 1652 of file matrices.c.
Referenced by zsl_mtx_pinv().
zsl_mtx_trans()
int zsl_mtx_trans (struct zsl_mtx * ma, struct zsl_mtx * mb)
Transposes the matrix 'ma' into matrix 'mb'. Note that output matrix 'mb' must have 'ma->sz_rows' columns, and 'ma->sz_cols' rows.
Parameters
ma Pointer to the input matrix to transpose.
mb Pointer to the output zsl_mtz.
Returns
0 if everything executed correctly, or -EINVAL if ma and mb are not compatibly shaped.
Definition at line 514 of file matrices.c.
Referenced by zsl_mtx_householder(), zsl_mtx_pinv(), zsl_mtx_qrd(), zsl_mtx_svd(), zsl_sta_mult_linear_reg(), zsl_sta_quad_fit(), and zsl_sta_weighted_mult_linear_reg().
zsl_mtx_vec_wedge()
int zsl_mtx_vec_wedge (struct zsl_mtx * m, struct zsl_vec * v)
Calculates the wedge product of n-1 vectors of size n, which are the rows of the matrix 'm'. This n-1 vectors must be linearly independent.
The wedge product is an extension of the cross product for dimension greater than 3. Given a set of n-1 vectors of size n, the wedge product calculates a n-dimensional vector that is perpendicular to all the others.
Parameters
m The input (n-1) x n matrix, with n > 3, whose rows are the linearly independent vectors to use in the wedge product.
v The output vector of dimension n, perpendicular to all the input vectors.
Returns
0 if everything executed correctly, or -EINVAL if n > 3, or if the input matrix isn't of the form (n-1) x n.
Definition at line 607 of file matrices.c.