Zephyr Scientific Library (zscilib): Comparison
Comparison
Vectors
Functions used to compare or verify vectors.
Functions
bool zsl_vec_is_equal (struct zsl_vec *v, struct zsl_vec *w, zsl_real_t eps)
Checks if two vectors are identical in size and content.
bool zsl_vec_is_nonneg (struct zsl_vec *v)
Checks if all elements in vector v are >= zero.
int zsl_vec_contains (struct zsl_vec *v, zsl_real_t val, zsl_real_t eps)
Checks if vector v contains val, returning the number of occurences.
int zsl_vec_sort (struct zsl_vec *v, struct zsl_vec *w)
Sorts the values in vector v from smallest to largest using quicksort, and assigns the sorted output to vector w.
Detailed Description
Functions used to compare or verify vectors.
Function Documentation
zsl_vec_contains()
int zsl_vec_contains (struct zsl_vec * v, zsl_real_t val, zsl_real_t eps)
Checks if vector v contains val, returning the number of occurences.
Parameters
v The vector to check.
val The value to check all coefficients for.
eps The margin for floating-point equality (ex. '1E-5').
Returns
The number of occurences of val withing range eps, 0 if no matching occurences were found, or a negative error code.
Definition at line 416 of file vectors.c.
Referenced by zsl_mtx_eigenvectors(), zsl_sta_mode(), zsl_sta_time_weighted_mean(), and zsl_vec_sort().
zsl_vec_is_equal()
bool zsl_vec_is_equal (struct zsl_vec * v, struct zsl_vec * w, zsl_real_t eps)
Checks if two vectors are identical in size and content.
Parameters
v The first vector.
w The second vector.
eps The margin for floating-point equality (ex. '1E-5').
Returns
true if the two vectors have the same size and the same values, otherwise false.
Definition at line 387 of file vectors.c.
zsl_vec_is_nonneg()
bool zsl_vec_is_nonneg (struct zsl_vec * v)
Checks if all elements in vector v are >= zero.
Parameters
v The vector to check.
Returns
true if all elements in 'v' are zero or positive, otherwise false.
Definition at line 405 of file vectors.c.
zsl_vec_sort()
int zsl_vec_sort (struct zsl_vec * v, struct zsl_vec * w)
Sorts the values in vector v from smallest to largest using quicksort, and assigns the sorted output to vector w.
Parameters
v The unsorted, input vector.
w The sorted, output vector.
Returns
0 if everything executed properly, otherwise a negative error code.
Definition at line 475 of file vectors.c.
Referenced by zsl_sta_data_range(), zsl_sta_percentile(), zsl_sta_time_weighted_mean(), zsl_sta_trim_mean(), and zsl_sta_weighted_median().